config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :users
  resources :orders
  resources :visas
  
  resources :contacts

end

app/models/visa.rb
class Visa < ActiveRecord::Base
    
end

app/controllers/visas_controller.rb
class VisasController < ApplicationController
  before_action :set_visa, only: [:show, :edit, :update, :destroy]

  # GET /visas
  # GET /visas.json
  def index
    @visas = Visa.all
  end

  # GET /visas/1
  # GET /visas/1.json
  def show
  end

  # GET /visas/new
  def new
    @visa = Visa.new
  end

  # GET /visas/1/edit
  def edit
  end

  # POST /visas
  # POST /visas.json
  def create
    @visa = Visa.new(visa_params)

    respond_to do |format|
      if @visa.save
        format.html { redirect_to @visa, notice: 'Visa was successfully created.' }
        format.json { render :show, status: :created, location: @visa }
      else
        format.html { render :new }
        format.json { render json: @visa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visas/1
  # PATCH/PUT /visas/1.json
  def update
    respond_to do |format|
      if @visa.update(visa_params)
        format.html { redirect_to @visa, notice: 'Visa was successfully updated.' }
        format.json { render :show, status: :ok, location: @visa }
      else
        format.html { render :edit }
        format.json { render json: @visa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visas/1
  # DELETE /visas/1.json
  def destroy
    @visa.destroy
    respond_to do |format|
      format.html { redirect_to visas_url, notice: 'Visa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visa
      @visa = Visa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visa_params
      params.require(:visa).permit(:name, :category, :price, :desc)
    end
end

app/helpers/visas_helper.rb
module VisasHelper
end

app/views/visas/_form.html.erb
<%= form_for(@visa) do |f| %>
  <% if @visa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visa.errors.count, "error") %> prohibited this visa from being saved:</h2>

      <ul>
      <% @visa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visas/edit.html.erb
<h1>Editing Visa</h1>

<%= render 'form' %>

<%= link_to 'Show', @visa %> |
<%= link_to 'Back', visas_path %>

app/views/visas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Price</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visas.each do |visa| %>
      <tr>
        <td><%= visa.name %></td>
        <td><%= visa.category %></td>
        <td><%= visa.price %></td>
        <td><%= visa.desc %></td>
        <td><%= link_to 'Show', visa %></td>
        <td><%= link_to 'Edit', edit_visa_path(visa) %></td>
        <td><%= link_to 'Destroy', visa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visa', new_visa_path %>

app/views/visas/new.html.erb
<h1>New Visa</h1>

<%= render 'form' %>

<%= link_to 'Back', visas_path %>

app/views/visas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @visa.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @visa.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @visa.price %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @visa.desc %>
</p>

<%= link_to 'Edit', edit_visa_path(@visa) %> |
<%= link_to 'Back', visas_path %>