config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :users
  resources :orders
  resources :visas
  
  resources :contacts

end

app/models/order.rb
class Order < ActiveRecord::Base
  
resourcify
has_many :passports
accepts_nested_attributes_for :passports, :allow_destroy => true
attr_writer :current_step
dragonfly_accessor :image do
      default 'public/images/default.png'
end
#validates_size_of :image, maximum: 5000.kilobytes
  
  def current_step
    @current_step || steps.first
  end
  
  def steps
    %w[first second passport]
  end
  
  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end
  
  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end
  
  def first_step?
    current_step == steps.first
  end
  
  def last_step?
    current_step == steps.last
  end
  
  
  
  def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end
   
   
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_amount, only: [:show]

  before_action :authenticate_user!, except: [:new, :create, :show]

  respond_to :html, :js

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
    format.html
    format.json
  end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    
  end



  # GET /orders/new
  def new
    
    session[:order_params] ||= {}
    @order = Order.new(session[:order_params])
    @order.current_step = session[:order_step]
    @visas = Visa.all

  end

  # GET /orders/1/edit
  def edit

  end

  # POST /orders
  # POST /orders.json
  def create
    
    @visas = Visa.all
    

    
    
    
    session[:order_params].deep_merge!(params[:order]) if params[:order]
    @order = Order.new(session[:order_params])
    @order.current_step = session[:order_step]
    @order.passports.build

    if @order.valid?
      if params[:back_button]
        @order.previous_step
      elsif @order.last_step?
        @order.save if @order.all_valid?
      else
        @order.next_step
      end
      session[:order_step] = @order.current_step
    end
    if @order.new_record?
      render "new"
    else
      #OrderMailer.order_created(@order).deliver_now
      
      session[:order_step] = session[:order_params] = nil
      flash[:notice] = "Order saved!"
      
      redirect_to @order
    end
  end
  
  
  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end
    
   def set_amount
     
    if @order.speed == 'Normal' 
    @readiness_date = @order.created_at  + 2.working.days 
    end
    
    if @order.speed == 'Urgent' 
    @readiness_date = @order.created_at  + 8.working.hours
    @additional3 = 10
    else
    @additional3 = 0
    end
    
    if @order.speed == 'Super Urgent' 
    @readiness_date = @order.created_at  + 3.working.hours
    @additional4 = 100
    else
    @additional4 = 0
    end
    
    if @order.fast_track == true
    @additional1 = 15
    else
    @additional1 = 0
    end
  
    if @order.private_letter == true
    @additional2 = 10
    else
    @additional2 = 0
    end

    
    @visa = Visa.find(@order.visa)
    @summa = @visa.price * @order.qty + @additional1 + @additional2 + @additional3 + @additional4
   end
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:image, :visa, :fast_track, :private_letter, :amount, :speed, 
      :border_point, :entry_date, :exit_date, :email, :customer_name, :phone, :passport_number, :passport_name, :nationality,
      :qty, :status, :passports_attributes => [:name, :nationality, :number, :gender, :birthday, :issue_date, :finish_date, :_destroy])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_confirmation.html.erb
<div class="actions">
    <%= f.submit %>
  </div>

app/views/orders/_first_step.html.erb
<h2>1 step</h2>

<div class="field">
    <%= f.label :qty %><br>
    
<div class="qty">
    <%= f.number_field :qty %>
  </div>
</div>

<div class="field">
  <%= f.label :nationality %><br>
  <select class="form-control" id="select" name="order[nationality]">
	<option value="AX">AALAND ISLANDS</option>
	<option value="AF">AFGHANISTAN</option>
	<option value="AL">ALBANIA</option>
	<option value="DZ">ALGERIA</option>
	<option value="AS">AMERICAN SAMOA</option>
	<option value="AD">ANDORRA</option>
	<option value="AO">ANGOLA</option>
	<option value="AI">ANGUILLA</option>
	<option value="AQ">ANTARCTICA</option>
	<option value="AG">ANTIGUA AND BARBUDA</option>
	<option value="AR">ARGENTINA</option>
	<option value="AM">ARMENIA</option>
	<option value="AW">ARUBA</option>
	<option value="AU">AUSTRALIA</option>
	<option value="AT">AUSTRIA</option>
	<option value="AZ">AZERBAIJAN</option>
	<option value="BS">BAHAMAS</option>
	<option value="BH">BAHRAIN</option>
	<option value="BD">BANGLADESH</option>
	<option value="BB">BARBADOS</option>
	<option value="BY">BELARUS</option>
	<option value="BE">BELGIUM</option>
	<option value="BZ">BELIZE</option>
	<option value="BJ">BENIN</option>
	<option value="BM">BERMUDA</option>
	<option value="BT">BHUTAN</option>
	<option value="BO">BOLIVIA</option>
	<option value="BA">BOSNIA AND HERZEGOWINA</option>
	<option value="BW">BOTSWANA</option>
	<option value="BV">BOUVET ISLAND</option>
	<option value="BR">BRAZIL</option>
	<option value="IO">BRITISH INDIAN OCEAN TERRITORY</option>
	<option value="BN">BRUNEI DARUSSALAM</option>
	<option value="BG">BULGARIA</option>
	<option value="BF">BURKINA FASO</option>
	<option value="BI">BURUNDI</option>
	<option value="KH">CAMBODIA</option>
	<option value="CM">CAMEROON</option>
	<option value="CA">CANADA</option>
	<option value="CV">CAPE VERDE</option>
	<option value="KY">CAYMAN ISLANDS</option>
	<option value="CF">CENTRAL AFRICAN REPUBLIC</option>
	<option value="TD">CHAD</option>
	<option value="CL">CHILE</option>
	<option value="CN">CHINA</option>
	<option value="CX">CHRISTMAS ISLAND</option>
	<option value="CO">COLOMBIA</option>
	<option value="KM">COMOROS</option>
	<option value="CK">COOK ISLANDS</option>
	<option value="CR">COSTA RICA</option>
	<option value="CI">COTE D'IVOIRE</option>
	<option value="CU">CUBA</option>
	<option value="CY">CYPRUS</option>
	<option value="CZ">CZECH REPUBLIC</option>
	<option value="DK">DENMARK</option>
	<option value="DJ">DJIBOUTI</option>
	<option value="DM">DOMINICA</option>
	<option value="DO">DOMINICAN REPUBLIC</option>
	<option value="EC">ECUADOR</option>
	<option value="EG">EGYPT</option>
	<option value="SV">EL SALVADOR</option>
	<option value="GQ">EQUATORIAL GUINEA</option>
	<option value="ER">ERITREA</option>
	<option value="EE">ESTONIA</option>
	<option value="ET">ETHIOPIA</option>
	<option value="FO">FAROE ISLANDS</option>
	<option value="FJ">FIJI</option>
	<option value="FI">FINLAND</option>
	<option value="FR">FRANCE</option>
	<option value="GF">FRENCH GUIANA</option>
	<option value="PF">FRENCH POLYNESIA</option>
	<option value="TF">FRENCH SOUTHERN TERRITORIES</option>
	<option value="GA">GABON</option>
	<option value="GM">GAMBIA</option>
	<option value="GE">GEORGIA</option>
	<option value="DE">GERMANY</option>
	<option value="GH">GHANA</option>
	<option value="GI">GIBRALTAR</option>
	<option value="GR">GREECE</option>
	<option value="GL">GREENLAND</option>
	<option value="GD">GRENADA</option>
	<option value="GP">GUADELOUPE</option>
	<option value="GU">GUAM</option>
	<option value="GT">GUATEMALA</option>
	<option value="GN">GUINEA</option>
	<option value="GW">GUINEA-BISSAU</option>
	<option value="GY">GUYANA</option>
	<option value="HT">HAITI</option>
	<option value="HM">HEARD AND MC DONALD ISLANDS</option>
	<option value="HN">HONDURAS</option>
	<option value="HK">HONG KONG</option>
	<option value="HU">HUNGARY</option>
	<option value="IS">ICELAND</option>
	<option value="IN">INDIA</option>
	<option value="ID">INDONESIA</option>
	<option value="IQ">IRAQ</option>
	<option value="IE">IRELAND</option>
	<option value="IL">ISRAEL</option>
	<option value="IT">ITALY</option>
	<option value="JM">JAMAICA</option>
	<option value="JP">JAPAN</option>
	<option value="JO">JORDAN</option>
	<option value="KZ">KAZAKHSTAN</option>
	<option value="KE">KENYA</option>
	<option value="KI">KIRIBATI</option>
	<option value="KW">KUWAIT</option>
	<option value="KG">KYRGYZSTAN</option>
	<option value="LA">LAO PEOPLE'S DEMOCRATIC REPUBLIC</option>
	<option value="LV">LATVIA</option>
	<option value="LB">LEBANON</option>
	<option value="LS">LESOTHO</option>
	<option value="LR">LIBERIA</option>
	<option value="LY">LIBYAN ARAB JAMAHIRIYA</option>
	<option value="LI">LIECHTENSTEIN</option>
	<option value="LT">LITHUANIA</option>
	<option value="LU">LUXEMBOURG</option>
	<option value="MO">MACAU</option>
	<option value="MG">MADAGASCAR</option>
	<option value="MW">MALAWI</option>
	<option value="MY">MALAYSIA</option>
	<option value="MV">MALDIVES</option>
	<option value="ML">MALI</option>
	<option value="MT">MALTA</option>
	<option value="MH">MARSHALL ISLANDS</option>
	<option value="MQ">MARTINIQUE</option>
	<option value="MR">MAURITANIA</option>
	<option value="MU">MAURITIUS</option>
	<option value="YT">MAYOTTE</option>
	<option value="MX">MEXICO</option>
	<option value="MC">MONACO</option>
	<option value="MN">MONGOLIA</option>
	<option value="MS">MONTSERRAT</option>
	<option value="MA">MOROCCO</option>
	<option value="MZ">MOZAMBIQUE</option>
	<option value="MM">MYANMAR</option>
	<option value="NA">NAMIBIA</option>
	<option value="NR">NAURU</option>
	<option value="NP">NEPAL</option>
	<option value="NL">NETHERLANDS</option>
	<option value="AN">NETHERLANDS ANTILLES</option>
	<option value="NC">NEW CALEDONIA</option>
	<option value="NZ">NEW ZEALAND</option>
	<option value="NI">NICARAGUA</option>
	<option value="NE">NIGER</option>
	<option value="NG">NIGERIA</option>
	<option value="NU">NIUE</option>
	<option value="NF">NORFOLK ISLAND</option>
	<option value="MP">NORTHERN MARIANA ISLANDS</option>
	<option value="NO">NORWAY</option>
	<option value="OM">OMAN</option>
	<option value="PK">PAKISTAN</option>
	<option value="PW">PALAU</option>
	<option value="PA">PANAMA</option>
	<option value="PG">PAPUA NEW GUINEA</option>
	<option value="PY">PARAGUAY</option>
	<option value="PE">PERU</option>
	<option value="PH">PHILIPPINES</option>
	<option value="PN">PITCAIRN</option>
	<option value="PL">POLAND</option>
	<option value="PT">PORTUGAL</option>
	<option value="PR">PUERTO RICO</option>
	<option value="QA">QATAR</option>
	<option value="RE">REUNION</option>
	<option value="RO">ROMANIA</option>
	<option value="RU">RUSSIAN FEDERATION</option>
	<option value="RW">RWANDA</option>
	<option value="SH">SAINT HELENA</option>
	<option value="KN">SAINT KITTS AND NEVIS</option>
	<option value="LC">SAINT LUCIA</option>
	<option value="PM">SAINT PIERRE AND MIQUELON</option>
	<option value="VC">SAINT VINCENT AND THE GRENADINES</option>
	<option value="WS">SAMOA</option>
	<option value="SM">SAN MARINO</option>
	<option value="ST">SAO TOME AND PRINCIPE</option>
	<option value="SA">SAUDI ARABIA</option>
	<option value="SN">SENEGAL</option>
	<option value="CS">SERBIA AND MONTENEGRO</option>
	<option value="SC">SEYCHELLES</option>
	<option value="SL">SIERRA LEONE</option>
	<option value="SG">SINGAPORE</option>
	<option value="SK">SLOVAKIA</option>
	<option value="SI">SLOVENIA</option>
	<option value="SB">SOLOMON ISLANDS</option>
	<option value="SO">SOMALIA</option>
	<option value="ZA">SOUTH AFRICA</option>
	<option value="GS">SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS</option>
	<option value="ES">SPAIN</option>
	<option value="LK">SRI LANKA</option>
	<option value="SD">SUDAN</option>
	<option value="SR">SURINAME</option>
	<option value="SJ">SVALBARD AND JAN MAYEN ISLANDS</option>
	<option value="SZ">SWAZILAND</option>
	<option value="SE">SWEDEN</option>
	<option value="CH">SWITZERLAND</option>
	<option value="SY">SYRIAN ARAB REPUBLIC</option>
	<option value="TW">TAIWAN</option>
	<option value="TJ">TAJIKISTAN</option>
	<option value="TH">THAILAND</option>
	<option value="TL">TIMOR-LESTE</option>
	<option value="TG">TOGO</option>
	<option value="TK">TOKELAU</option>
	<option value="TO">TONGA</option>
	<option value="TT">TRINIDAD AND TOBAGO</option>
	<option value="TN">TUNISIA</option>
	<option value="TR">TURKEY</option>
	<option value="TM">TURKMENISTAN</option>
	<option value="TC">TURKS AND CAICOS ISLANDS</option>
	<option value="TV">TUVALU</option>
	<option value="UG">UGANDA</option>
	<option value="UA">UKRAINE</option>
	<option value="AE">UNITED ARAB EMIRATES</option>
	<option value="GB">UNITED KINGDOM</option>
	<option value="US">UNITED STATES</option>
	<option value="UM">UNITED STATES MINOR OUTLYING ISLANDS</option>
	<option value="UY">URUGUAY</option>
	<option value="UZ">UZBEKISTAN</option>
	<option value="VU">VANUATU</option>
	<option value="VE">VENEZUELA</option>
	<option value="VN">VIET NAM</option>
	<option value="WF">WALLIS AND FUTUNA ISLANDS</option>
	<option value="EH">WESTERN SAHARA</option>
	<option value="YE">YEMEN</option>
	<option value="ZM">ZAMBIA</option>
	<option value="ZW">ZIMBABWE</option>
</select>

<label>Select propose:</label><br>

<select class="form-control" name="category1" id="category1">
						<option value="">Select Purpose</option>
						<option value="business">Business</option>
						<option value="tourism">Tourism</option>
					</select>
   
   
  <div class="field">
    <%= f.label :visa %><br>
    <select disabled="disabled" class="form-control" id="category2" name="order[visa]">
      <%= options_for_select(@visas.map{ |c| [c.name, c.id, { 'rel' => c.category}] }) %>
    </select><br>
    <div>

    </div>
    </div>
  <div class="field">
    <label for="order_fast_track">Fast track</label><br>
    <input name="order[fast_track]" type="hidden" value="0" /><input type="checkbox" value="1" name="order[fast_track]" id="fast_track">
  </div>
  <div class="field">
    <%= f.label :private_letter %><br>
    <%= f.check_box :private_letter %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <select class="form-control" id="select" name="order[speed]">
	  <option value="Normal">Normal</option>
	  <option value="Urgent">Urgent</option>
	  <option value="Super Urgent">Super Urgent</option>
	  </select>
  </div>
  <div class="field">
    <%= f.label :border_point %><br>
    <select class="form-control" id="select" name="order[border_point]">
	  <option value="Hanoi">Hanoi int airport</option>
	  <option value="HCMC">Ho Chi Mihn City</option>
	  </select>
  </div>
  <div class="field">
    <%= f.label :entry_date %><br>
  <div class="input-group">
      
  <span>
    <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
  </span>

  <input type="text" data-provide='datepicker' name="order[entry_date]" id="entry_date">
  </div>
  </div>
  <div class="field">
    <%= f.label :exit_date %><br>
    <div class="input-group">
      
  <span>
    <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
  </span>
  <input type="text" data-provide='datepicker' name="order[exit_date]" id="exit_date">
  </div>
    </div>

  <div id="daysQTY"></div>

app/views/orders/_form.html.erb
<div id="form" data-remote="true" class="form-group">


<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= render 'steps_tabs' %>
  <%= render "#{@order.current_step}_step", :f => f %>
  <%= render 'visa_price' %>
  <div class="form-group">
  <% if @order.current_step != "first"  %>
  <%= button_tag(type: 'submit', class: "btn btn-warning", name:  "back_button" ) do %>
     <i class="fa fa-step-backward"></i> Back

  <% end %>
  <% else %>
  <% end %>
  
  <%= button_tag(type: 'submit', class: "btn btn-warning") do %>Next
 <i class="fa fa-step-forward"></i>
  <% end %>
  
  
  

  </div>
  
  
  
<% end %>
</div>

app/views/orders/_passport_fields.html.erb
<div class="nested-fields">
<div class="row">
  
          <div class="field">
          <%= f.label :name, "Full Name" %><br/>
          <%= f.text_field :name %>
          </div>
          <div class="field">
          <%= f.label :number, "Passport Number" %><br/>
          <%= f.text_field :number%>
          </div>            
          <div class="field">
          <%= f.label :issue_date, "Passport issue date" %><br/>
          <%= f.date_select :issue_date%>
          </div>
          
          <div class="field">
          <%= f.label :finish_date, "Passport finish date" %><br/>
          <%= f.date_select :finish_date%>
          </div>         
          
          
          <div>
              <%= f.label :gender, "Gender:" %><br/>
              <span class="input-group-addon">
              <input type="radio" id="GenderChoice1"name="order[gender]" value="male" class="form-control">
              <i class="fa fa-male"></i>
              Male</input>
              <input type="radio" id="GenderChoice2"name="order[gender]" value="female" class="form-control">
              <i class="fa fa-female"></i> Female</input>
              </span>
          </div>
          <div class="field">
          <%= f.label :birhday, "Date of birth" %><br/>
          <%= f.date_select :birhday %>
          </div>
          <div class="field">
          <%= f.label :nationality, "Nationality" %><br/>
          <%= f.text_field :nationality %><br/>
          </div>
            <%= link_to_remove_association "remove", f %>

</div>
</div>

app/views/orders/_passport_step.html.erb
<h2>Passport</h2>

<div>
    <%= f.label :image %>
    <%= f.file_field :image %>
 </div>

<%= f.fields_for :passports do |builder| %>
<div class="links">
      <%= link_to_add_association 'add task', f, :passports %>
    </div>
    <% render 'orders/passport_fields',:f => builder %>
<% end %>

app/views/orders/_second_step.html.erb
<h2>2 step</h2>
<div class="field">
    <%= f.label :email %><br>
    <div class="input-group">
      
		  <span>
		  	<i class="fa fa-at"></i>
		  </span>
    <input type="text" placeholder=" Your email" name="order[email]">

   </div>
</div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <div class="input-group">
      
		  <span>
		  	<i class="fa fa-user"></i>
		  </span>
    <input type="text" placeholder=" Your name" name="order[customer_name]">

   </div>
</div>
  <div class="field">
    <%= f.label :phone %><br>
    <div class="input-group">
      
		  <span>
		  	<i class="fa fa-phone"></i>
		  </span>
    <input type="text" placeholder=" Your phone" name="order[phone]">

   </div>
</div>

app/views/orders/_steps_tabs.html.erb
<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
</ul>

app/views/orders/_visa_price.html.erb
<h3>TTTT</h3>
<%= @order.amount %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>

      <th>Visa</th>
      <th>Fast track</th>
      <th>Private letter</th>
      <th>Amount</th>
      <th>Speed</th>
      <th>Border point</th>
      <th>Entry date</th>
      <th>Email</th>
      <th>Customer name</th>
      <th>Phone</th>
      <th>Passport number</th>
      <th>Passport name</th>
      <th>Nationality</th>
      <th>Passport issued</th>
      <th>Passport end</th>
      <th>Gender</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to image_tag(order.image.thumb('100x100').url), order.image.url  %></td>
        <td><%= order.visa %></td>
        <td><%= order.fast_track %></td>
        <td><%= order.private_letter %></td>
        <td><%= order.amount %></td>
        <td><%= order.speed %></td>
        <td><%= order.border_point %></td>
        <td><%= order.entry_date %></td>
        <td><%= order.email %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.phone %></td>
        <td><%= order.passport_number %></td>
        <td><%= order.passport_name %></td>
        <td><%= order.nationality %></td>
        <td><%= order.passport_issued %></td>
        <td><%= order.passport_end %></td>
        <td><%= order.gender %></td>
        <td><%= order.birthday %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
<div id="task-form" style="display:none;">
  
  FUCK
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>
<% if user_signed_in? %>
<%= link_to 'Back', orders_path %>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order Number:</strong>
  <%= @order.id %>
</p>
<p>
<%= link_to image_tag(@order.image.thumb('100x100').url), @order.image.url  %>
</p>
<p>
  <strong>Order Created:</strong>
  <%= @order.created_at %>
</p>
<p>
  <strong>Your approval letter readiness date:</strong>
  <%= @readiness_date %>
</p>
<p>
  <strong>TOTAL:</strong>
  <%= @summa %>
</p>

<p>
  <strong>QTY of visitors:</strong>
  <%= @order.qty %>
</p>


<p>
  <strong>Visa:</strong>
  <%= @order.visa %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  
  <% if @order.fast_track == true %>
  <strong>Fast track:</strong>
  <%= @order.fast_track %>
  <% end %>
</p>

<p>
  <% if @order.private_letter == true %>
  <strong>Private letter:</strong>
  <%= @order.private_letter %>
  <% end %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @order.speed %>
</p>

<p>
  <strong>Border point:</strong>
  <%= @order.border_point %>
</p>

<ol>
  <% for passport in @order.passports %>
   <li><%=h passport.name%></li>
   <li><%=h passport.number%></li>
   <li><%=h passport.nationality%></li>
   <li><%=h passport.gender%></li>
   <li><%=h passport.finish_date%></li>
   <li><%=h passport.birhday%></li>
  <% end %>
</ol>

<p>
  <strong>Entry date:</strong>
  <%= @order.entry_date %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @order.nationality %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>